stages:
  - build
  - trigger

variables:
  GECODE_ROOT: "$CI_PROJECT_DIR/vendor/gecode"
  GUROBI_ROOT: "$CI_PROJECT_DIR/vendor/gurobi"
  CPLEX_ROOT: "$CI_PROJECT_DIR/vendor/CPLEX_Studio"
  OSICBC_ROOT: "$CI_PROJECT_DIR/vendor/cbc"

.build_template: &build_definition
  stage: build
  script:
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:$ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/minizinc%2Fvendor/jobs/artifacts/master/download?job=vendor:${MZNARCH}"
    - unzip -q vendor.zip
    - rm -rf build
    - mkdir -p build
    - cd build
    - cmake -G"$CMAKE_ARCH" -DCMAKE_BUILD_TYPE=Release -v .. -DBUILD_REF=$CI_PIPELINE_ID -DUSE_PROPRIETARY=OFF -DGECODE_NO_MPFR=ON -DCMAKE_INSTALL_PREFIX="$CI_PROJECT_DIR/minizinc"
    - cmake --build .  --config Release
    - cmake --build .  --config Release --target install
  artifacts:
    paths:
      - minizinc/


build:linux:
  <<: *build_definition
  image: dekker1/minibuild:cpp
  variables:
    MZNARCH: "linux"
    CMAKE_ARCH: "Unix Makefiles"
  tags:
    - linux
    - docker

build:musl:
  <<: *build_definition
  image: dekker1/minibuild:alpine
  variables:
    MZNARCH: "musl"
    CMAKE_ARCH: "Unix Makefiles"
  tags:
    - linux
    - docker

build:osx:
  <<: *build_definition
  stage: build
  variables:
    MZNARCH: "osx"
    CMAKE_ARCH: "Xcode"
  tags:
    - osx
    - cmake
    - cpp

build:win64:
  <<: *build_definition
  variables:
    MZNARCH: "win64"
    CMAKE_ARCH: "Visual Studio 14 2015 Win64"
    GECODE_ROOT: "%CI_PROJECT_DIR%/vendor/gecode"
    GUROBI_ROOT: "%CI_PROJECT_DIR%/vendor/gurobi"
    CPLEX_ROOT: "%CI_PROJECT_DIR%/vendor/CPLEX_Studio"
    OSICBC_HOME: "%CI_PROJECT_DIR%/vendor/cbc"
  script:
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" "https://gitlab.com/api/v4/projects/minizinc%%2Fvendor/jobs/artifacts/master/download?job=vendor:win64"
    - unzip -q vendor.zip
    - if not exist "build" mkdir build
    - cd build
    - cmake -G"%CMAKE_ARCH%" .. -DBUILD_REF=%CI_PIPELINE_ID% -DSHARED_GECODE=TRUE -DUSE_PROPRIETARY=OFF -DCMAKE_INSTALL_PREFIX="%CI_PROJECT_DIR%/minizinc"
    - cmake --build .  --config Release
    - cmake --build .  --config Release --target install
  tags:
    - win64
    - cmake
    - cpp

# ----------- Trigger FindMUS pipeline -----------

trigger:findmus:
  stage: trigger
  image: dekker1/minibuild:package
  script:
  - "curl --request POST --form token=$TRIGGER --form ref=master https://gitlab.com/api/v4/projects/minizinc%2FFindMUS/trigger/pipeline"
  dependencies: []
  tags: [linux, docker]
  only: [develop]
