stages:
  - build
  - test

build:linux:
  stage: build
  image: gcc:latest
  before_script:
    - apt-get update && apt-get -y install cmake
  script:
    - mkdir build
    - cd build
    - bash ../BUILD.sh
    - mv mzn2fzn mzn-fzn solns2out ../
  artifacts:
     paths:
       - mzn2fzn
       - mzn-fzn
       - solns2out
  tags:
     - linux

build:osx:
  stage: build
  script:
    - mkdir build
    - cd build
    - bash ../BUILD.sh
    - mv mzn2fzn mzn-fzn solns2out ../
  artifacts:
     paths:
       - mzn2fzn
       - mzn-fzn
       - solns2out
  tags:
     - mac

build:windows:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -G"Visual Studio 12 Win64" -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - mv Release/mzn2fzn.exe Release/mzn-fzn.exe Release/solns2out.exe ../
  artifacts:
     paths:
       - mzn2fzn.exe
       - mzn-fzn.exe
       - solns2out.exe
  tags:
     - windows

test:mzn20_fd:linux:
  stage: test
  image: ubuntu:latest
  script:
     - cd tests
     - export PATH="$(pwd)/..":"$(pwd)/scripts":"$PATH"
     - bash run-tests mzn20_fd .mzn unit examples
  dependencies:
     - build:linux
  tags:
     - linux

test:mzn-fzn_fd:linux:
  stage: test
  image: ubuntu:latest
  script:
     - cd tests
     - export PATH="$(pwd)/..":"$(pwd)/scripts":"$PATH"
     - bash run-tests mzn-fzn_fd .mzn unit examples
  dependencies:
     - build:linux
  tags:
     - linux

test:mzn20_fd:osx:
  stage: test
  script:
     - cd tests
     - export PATH="$(pwd)/..":"$(pwd)/scripts":"$PATH"
     - bash run-tests mzn20_fd .mzn unit examples
  dependencies:
     - build:osx
  tags:
     - mac

test:mzn-fzn_fd:osx:
  stage: test
  script:
     - cd tests
     - export PATH="$(pwd)/..":"$(pwd)/scripts":"$PATH"
     - bash run-tests mzn-fzn_fd .mzn unit examples
  dependencies:
     - build:osx
  tags:
     - mac
