stages:
  - build
  - test
  - trigger

.download_script: &download_script
  - curl --location --header "PRIVATE-TOKEN:$ACCESS_TOKEN" --silent https://gitlab.com/api/v4/snippets/1796163/raw | tr -d '\r' > download.sh

variables:
  # Vendor solver locations
  Gecode_ROOT: "$CI_PROJECT_DIR/vendor/gecode"
  Gurobi_ROOT: "$CI_PROJECT_DIR/vendor/gurobi"
  CPlex_ROOT: "$CI_PROJECT_DIR/vendor/CPLEX_Studio/cplex"
  OsiCBC_ROOT: "$CI_PROJECT_DIR/vendor/cbc"
  SCIP_ROOT: "$CI_PROJECT_DIR/vendor/scip"
  Xpress_ROOT: "$CI_PROJECT_DIR/vendor/xpressmp"
  # CCache settings
  CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"
  CCACHE_MAXSIZE: "100M"

# ----------- Build MiniZinc -----------

.build_template: &build_definition
  stage: build
  interruptible: true
  before_script: *download_script
  script:
    - sh download.sh vendor master vendor:${MZNARCH} vendor.zip
    - unzip -q vendor.zip
    - cmake -S . -B build -G"$CMAKE_ARCH" -DCMAKE_BUILD_TYPE=Release -DBUILD_REF=$CI_PIPELINE_ID -DUSE_PROPRIETARY=OFF -DCMAKE_INSTALL_PREFIX="$CI_PROJECT_DIR/minizinc"
    - cmake --build build --config Release --target install
  artifacts:
    paths: [minizinc/]
  cache:
    key: "$CI_JOB_NAME"
    paths: [.ccache, vendor.zip*]
  only: [tags, merge_requests, pipelines, develop, master]

build:linux:
  <<: *build_definition
  image: dekker1/minibuild:cpp
  variables:
    MZNARCH: "linux"
    CMAKE_ARCH: "Ninja"
  tags: [linux, docker]

build:musl:
  <<: *build_definition
  image: dekker1/minibuild:alpine
  variables:
    MZNARCH: "musl"
    CMAKE_ARCH: "Ninja"
  tags: [linux, docker]

build:osx:
  <<: *build_definition
  stage: build
  variables:
    MZNARCH: "osx"
    CMAKE_ARCH: "Ninja"
  tags: [osx, cmake, cpp]

build:win64:
  stage: build
  interruptible: true
  variables:
    MZNARCH: "win64"
    CMAKE_ARCH: "Visual Studio 15 2017 Win64"
  before_script:
    - curl -o download.sh --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" --silent https://gitlab.com/api/v4/snippets/1796163/raw
    - dos2unix download.sh
  script:
    - sh download.sh vendor master vendor:%MZNARCH% vendor.zip
    - unzip -q vendor.zip
    - cmake -S . -B build -G"%CMAKE_ARCH%" -DBUILD_REF=%CI_PIPELINE_ID% -DUSE_PROPRIETARY=OFF -DCMAKE_INSTALL_PREFIX="%CI_PROJECT_DIR%/minizinc"
    - cmake --build build --config Release --target install
  artifacts:
    paths: [minizinc/]
  cache:
    key: "win64"
    paths: [vendor.zip*]
  tags: [win64, cmake, cpp]
  only: [tags, merge_requests, pipelines, develop, master]

build:wasm_complete:
  image: emscripten/emsdk
  stage: build
  interruptible: true
  variables:
    MZNARCH: "wasm"
    CMAKE_ARCH: "Unix Makefiles"
  tags: [docker, high-mem]
  before_script: *download_script
  script:
    - apt-get update && apt-get install -qq python3
    - sh download.sh vendor master vendor:wasm vendor.zip
    - unzip -q vendor.zip
    - emcmake cmake -S . -B build -G"$CMAKE_ARCH" -DCMAKE_FIND_ROOT_PATH="/" -DCMAKE_BUILD_TYPE=MinSizeRel -v -DBUILD_REF=$CI_PIPELINE_ID -DUSE_PROPRIETARY=OFF -DCMAKE_INSTALL_PREFIX="$CI_PROJECT_DIR/minizinc"
    - cmake --build build --config MinSizeRel --target install
  artifacts:
    paths: [minizinc/]
  cache:
    key: "$CI_JOB_NAME"
    paths: [.ccache, vendor.zip*]
  only: [tags, merge_requests, pipelines, develop, master]
  when: manual

build:wasm_minimal:
  image: emscripten/emsdk
  stage: build
  interruptible: true
  variables:
    MZNARCH: "wasm"
    CMAKE_ARCH: "Unix Makefiles"
  tags: [docker]
  before_script: *download_script
  script:
    - apt-get update && apt-get install -qq python3
    - sh download.sh vendor master vendor:wasm vendor.zip
    - unzip -q vendor.zip
    - emcmake cmake -S . -B build -G"$CMAKE_ARCH" -DCMAKE_BUILD_TYPE=MinSizeRel -v -DBUILD_REF=$CI_PIPELINE_ID -DUSE_PROPRIETARY=OFF -DCMAKE_INSTALL_PREFIX="$CI_PROJECT_DIR/minizinc"
    - cmake --build build --config MinSizeRel --target install
  artifacts:
    paths: [minizinc/]
  cache:
    key: "$CI_JOB_NAME"
    paths: [.ccache, vendor.zip*]
  only: [tags, merge_requests, pipelines, develop, master]
  when: manual

# ----------- Test Suite -----------

test:format:
  stage: test
  interruptible: true
  image: dekker1/minibuild:clang-format
  script:
    - cmake -S . -B build -GNinja -DCLANG_FORMAT_EXECUTABLE="run-clang-format" -DCLANG_FORMAT_FLAGS="--color always"
    - cmake --build build --target format
  tags: [linux, docker]
  only:
    changes:
      - "**/*.{cpp,c,h,hh,hpp}"
      - .clang-format
    refs:
      - merge_requests
  needs: []

test:analyse:
  stage: test
  interruptible: true
  image: dekker1/minibuild:clang-tidy
  variables:
    MZNARCH: "linux"
    CMAKE_ARCH: "Ninja"
  before_script: *download_script
  script:
    - sh download.sh vendor master vendor:${MZNARCH} vendor.zip
    - unzip -q vendor.zip
    - cmake -S . -B build -G"$CMAKE_ARCH" -DCMAKE_CXX_CLANG_TIDY="clang-tidy" -DCMAKE_BUILD_TYPE="Debug"
    - cmake --build build --config Debug
  tags: [linux, docker]
  only:
    changes:
      - "**/*.{cpp,c,h,hh,hpp}"
      - .clang-tidy
    refs:
      - merge_requests
  cache:
    key: "$CI_JOB_NAME"
    paths: [.ccache, vendor.zip*]
  needs: []

include: 
- local: '/tests/.gitlab-ci-testing-pipeline.yml'

# ----------- Trigger FindMUS pipeline -----------

trigger:findmus:
  stage: trigger
  trigger:
    project: minizinc/FindMUS
    branch: develop
  only: [develop]
