stages:
  - build
  - test

build:linux:
  stage: build
  image: dekker1/cmake:latest
  variables:
    CMAKE_ARCH: "Unix Makefiles"
  script:
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:$ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/minizinc%2Fvendor/jobs/artifacts/master/download?job=vendor:linux"
    - unzip -q vendor.zip
    - mkdir -p build
    - cd build
    - cmake -G"$CMAKE_ARCH" -v .. -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DGECODE_HOME="$CI_PROJECT_DIR/vendor/gecode" -DOSICBC_HOME="$CI_PROJECT_DIR/vendor/CBC" -DCMAKE_INSTALL_PREFIX="$CI_PROJECT_DIR/minizinc"
    - cmake --build .  --config Release
    - cmake --build .  --config Release --target install
  artifacts:
    paths:
      - minizinc/
  tags:
     - linux
     - docker
  cache:
    key: "linux_$CI_COMMIT_REF_SLUG"
    paths:
      - build/

build:osx:
  stage: build
  variables:
    CMAKE_ARCH: "Xcode"
    GUROBI_DIR: "/Library/gurobi801/mac64"
    CPLEX_DIR: "~/Applications/IBM/ILOG/CPLEX_Studio1271"
  script:
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:$ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/minizinc%2Fvendor/jobs/artifacts/master/download?job=vendor:osx"
    - unzip -q vendor.zip
    - mkdir -p build
    - cd build
    - cmake -G"$CMAKE_ARCH" .. -DGECODE_HOME="$CI_PROJECT_DIR/vendor/gecode" -DBUILD_GUROBI_PLUGIN=ON -DGUROBI_HOME="$GUROBI_DIR" -DOSICBC_HOME="$CI_PROJECT_DIR/vendor/CBC" -DBUILD_CPLEX_PLUGIN=ON -DCPLEX_STUDIO_DIR="$CPLEX_DIR" -DCMAKE_INSTALL_PREFIX="$CI_PROJECT_DIR/minizinc"
    - cmake --build .  --config Release
    - cmake --build .  --config Release --target install
  artifacts:
    paths:
      - minizinc/
  tags:
     - osx
     - cmake
     - cpp
     - gurobi
  cache:
    key: "osx_$CI_COMMIT_REF_SLUG"
    paths:
      - build/

build:win32:
  stage: build
  variables:
    CMAKE_ARCH: "Visual Studio 14 2015"
    GUROBI_DIR: "C:/gurobi701/win32"
    CPLEX_DIR: "C:/Program Files/IBM/ILOG/CPLEX_Studio127"
  script:
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" "https://gitlab.com/api/v4/projects/minizinc%%2Fvendor/jobs/artifacts/master/download?job=vendor:win32"
    - unzip -q vendor.zip
    - if not exist "build" mkdir build
    - cd build
    - cmake -G"%CMAKE_ARCH%" .. -DGECODE_HOME="%CI_PROJECT_DIR%/vendor/gecode" -DSHARED_GECODE=TRUE -DBUILD_GUROBI_PLUGIN=ON -DGUROBI_HOME="%GUROBI_DIR%" -DOSICBC_HOME="%CI_PROJECT_DIR%/vendor/CBC" -DCMAKE_INSTALL_PREFIX="%CI_PROJECT_DIR%/minizinc"
    - cmake --build .  --config Release
    - cmake --build .  --config Release --target install
  artifacts:
    paths:
      - minizinc/
  tags:
     - win32
     - cmake
     - cpp
     - gurobi
  cache:
    key: "win32_$CI_COMMIT_REF_SLUG"
    paths:
      - build/

build:win64:
  stage: build
  variables:
    CMAKE_ARCH: "Visual Studio 14 2015 Win64"
    GUROBI_DIR: "C:/gurobi701/win64"
    CPLEX_DIR: "C:/Program Files/IBM/ILOG/CPLEX_Studio127"
  script:
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" "https://gitlab.com/api/v4/projects/minizinc%%2Fvendor/jobs/artifacts/master/download?job=vendor:win64"
    - unzip -q vendor.zip
    - if not exist "build" mkdir build
    - cd build
    - cmake -G"%CMAKE_ARCH%" .. -DGECODE_HOME="%CI_PROJECT_DIR%/vendor/gecode" -DSHARED_GECODE=TRUE -DBUILD_GUROBI_PLUGIN=ON -DGUROBI_HOME="%GUROBI_DIR%" -DOSICBC_HOME="%CI_PROJECT_DIR%/vendor/CBC" -DBUILD_CPLEX_PLUGIN=ON -DCPLEX_STUDIO_DIR="%CPLEX_DIR%" -DCMAKE_INSTALL_PREFIX="%CI_PROJECT_DIR%/minizinc"
    - cmake --build .  --config Release
    - cmake --build .  --config Release --target install
  artifacts:
    paths:
      - minizinc/
  tags:
     - win64
     - cmake
     - cpp
     - gurobi
  cache:
    key: "win64_$CI_COMMIT_REF_SLUG"
    paths:
      - build/
