stages:
  - build
  - test

# build:linux:
#   stage: build
#   image: gcc:latest
#   before_script:
#     - apt-get update && apt-get -y install cmake
#   script:
#     - mkdir build
#     - cd build
#     - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/..
#     - cmake --build . --target install -- -j4
#   artifacts:
#      paths:
#        - bin/
#   tags:
#      - linux

build:osx:
  stage: build
  variables:
    CMAKE_ARCH: "Xcode"
    GUROBI_DIR: "/Library/gurobi751/mac64"
  script:
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:$ACCESS_TOKEN" "https://gitlab.com/api/v4/projects/minizinc%2Fvendor/jobs/artifacts/master/download?job=vendor:osx"
    - unzip -q vendor.zip
    - mkdir -p build
    - cd build
    - cmake -G"$CMAKE_ARCH" .. -DGECODE_HOME="$CI_PROJECT_DIR/vendor/gecode" -DGUROBI_HOME="$GUROBI_DIR" -DBUILD_GUROBI_PLUGIN=1 -DOSICBC_HOME="$CI_PROJECT_DIR/vendor/CBC" -DCMAKE_INSTALL_PREFIX="$CI_PROJECT_DIR/minizinc"
    - cmake --build .  --config Release
    - cmake --build .  --config Release --target install
  artifacts:
    paths:
      - minizinc/
  tags:
     - osx
     - cmake
     - cpp
     - gurobi
  cache:
    key: "osx_$CI_COMMIT_REF_SLUG"
    paths:
      - build/

build:win32:
  stage: build
  variables:
    CMAKE_ARCH: "Visual Studio 14 2015"
    GUROBI_DIR: "C:/gurobi701/win32"
  script:
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" "https://gitlab.com/api/v4/projects/minizinc%%2Fvendor/jobs/artifacts/master/download?job=vendor:win32"
    - unzip -q vendor.zip
    - if not exist "build" mkdir build
    - cd build
    - cmake -G"%CMAKE_ARCH%" .. -DGECODE_HOME="%CI_PROJECT_DIR%/vendor/gecode" -DGUROBI_HOME="%GUROBI_DIR%" -DBUILD_GUROBI_PLUGIN=1 -DOSICBC_HOME="%CI_PROJECT_DIR%/vendor/CBC" -DCMAKE_INSTALL_PREFIX="%CI_PROJECT_DIR%/minizinc"
    - cmake --build .  --config Release
    - cmake --build .  --config Release --target install
  artifacts:
    paths:
      - minizinc/
  tags:
     - win32
     - cmake
     - cpp
     - gurobi
  cache:
    key: "win32_$CI_COMMIT_REF_SLUG"
    paths:
      - build/

build:win64:
  stage: build
  variables:
    CMAKE_ARCH: "Visual Studio 14 2015 Win64"
    GUROBI_DIR: "C:/gurobi701/win64"
  script:
    - curl --silent -o vendor.zip --location --header "PRIVATE-TOKEN:%ACCESS_TOKEN%" "https://gitlab.com/api/v4/projects/minizinc%%2Fvendor/jobs/artifacts/master/download?job=vendor:win64"
    - unzip -q vendor.zip
    - if not exist "build" mkdir build
    - cd build
    - cmake -G"%CMAKE_ARCH%" .. -DGECODE_HOME="%CI_PROJECT_DIR%/vendor/gecode" -DGUROBI_HOME="%GUROBI_DIR%" -DBUILD_GUROBI_PLUGIN=1 -DOSICBC_HOME="%CI_PROJECT_DIR%/vendor/CBC" -DCMAKE_INSTALL_PREFIX="%CI_PROJECT_DIR%/minizinc"
    - cmake --build .  --config Release
    - cmake --build .  --config Release --target install
  artifacts:
    paths:
      - minizinc/
  tags:
     - win64
     - cmake
     - cpp
     - gurobi
  cache:
    key: "win64_$CI_COMMIT_REF_SLUG"
    paths:
      - build/
