[workspace]
resolver = "3"
members = [
    "tools/minizinc_ffi",
    "tools/coverage_extractor",
    "crates/zos-bootstrap",
    "crates/constant_analyzer",
    "crates/constant_analyzer_macros",
    "crates/minizinc_introspector",
    "crates/minizinc_macro",
    "crates/minizinc_macro_test",
    "doc_organizer",
    "doc_to_minizinc_data",
    "embedding_analyzer",
    "zos-bootstrap-main",
    "crates/minizinc_output_parser",
    "rust_lattice_project",
    "crates/rust_file_finder",
    "crates/zos-fast-query",
    "crates/ragit-string-utils",
    # "crates/vocabulary_dfa_generator",
    # "crates/vocabulary_dfa_lib",
    # "crates/dfa_tester",
    "crates/backpack_tool", "crates/code_search_tool",
    "vendor/hugging-face-dataset-validator-rust",
]

[patch.crates-io]
hf-dataset-validator = { path = "vendor/hugging-face-dataset-validator-rust" }
arrow-arith = { path = "vendor/arrow-arith-patched" }

[workspace.dependencies]
arrow = "56.0.0"
parquet = "56.0.0"