% Parameters for Lambda Calculus Embedding on Partitioned Sphere (Version 4)

include "embedding_params_core_composed_v3.mzn"; % Use new composed core parameters
include "embedding_params_kappa_composed.mzn";
include "embedding_params_other_composed.mzn";
include "embedding_params_relations_v4.mzn"; % Use new simplified relations
include "embedding_params_vector_composed_v3.mzn"; % Use new composed vector params
