% 🧩✨ -- Composing the Vector Axiom Parameters: The Guiding Truths of Abstract Space! (Version 3) -- 🎶🌌💡

include "embedding_params_vector_v2.mzn"; % Use new version without num_vec
include "embedding_params_vector_L10_derived_header.mzn"; % 🔢✨ -- The Quantized Vector Axiom Coefficients! -- 📏💡
include "embedding_params_vector_L11_alpha_coeff_scaled.mzn"; % ➡️🔢 -- Alpha Coefficients, Quantized! -- ✨
include "embedding_params_vector_L12_beta_coeff_scaled.mzn";  % ➡️🔢 -- Beta Coefficients, Quantized! -- ✨
