#!/bin/bash

# Define paths
MINIZINC_OUTPUT_DIR="/data/data/com.termux/files/home/storage/github/libminizinc/minizinc_output_single_file"
TEST_MODEL="${MINIZINC_OUTPUT_DIR}/ast_model.mzn"
TEST_DATA="${MINIZINC_OUTPUT_DIR}/ast_data.dzn"
MINIZINC_EXECUTABLE="/data/data/com.termux/files/home/storage/github/libminizinc/build/minizinc"

echo "--- Starting MiniZinc Hang Debug Script ---"

# 1. Ensure zos-bootstrap has generated the files
echo "Ensuring zos-bootstrap has generated ast_model.mzn and ast_data.dzn..."
cargo run --package zos-bootstrap -- test-ast-to-mini-zinc --file-path /data/data/com.termux/files/home/storage/github/libminizinc/minimal_test.rs
if [ $? -ne 0 ]; then
    echo "Error: zos-bootstrap failed to run."
    exit 1
fi
echo "Files generated by zos-bootstrap."

# 2. Generate a temporary script to call MiniZinc with timeout
echo "Generating temporary MiniZinc execution script with timeout..."
TEMP_MINIZINC_SCRIPT="${MINIZINC_OUTPUT_DIR}/run_minizinc_debug.sh"
echo "#!/bin/bash" > "${TEMP_MINIZINC_SCRIPT}"
echo "timeout 10s ${MINIZINC_EXECUTABLE} ${TEST_MODEL} ${TEST_DATA} --time-limit 10000 --verbose --verbose-compilation" >> "${TEMP_MINIZINC_SCRIPT}"
chmod +x "${TEMP_MINIZINC_SCRIPT}"
echo "Temporary MiniZinc debug script generated: ${TEMP_MINIZINC_SCRIPT}"
echo "To run MiniZinc for debugging, execute: ${TEMP_MINIZINC_SCRIPT}"

# The direct MiniZinc execution and error checking are now commented out
# MINIZINC_OUTPUT=$("${MINIZINC_EXECUTABLE}" "${TEST_MODEL}" "${CHUNK_DZN_FILE}" --output-limit=10 --time-limit=10s 2>&1)
# MINIZINC_EXIT_CODE=$?

# echo "--- MiniZinc Output ---"
# echo "${MINIZINC_OUTPUT}"
# echo "--- End MiniZinc Output ---"

# # 4. Check for the expected error
# EXPECTED_ERROR="Error: type error: undefined identifier 'num_words'"
# if echo "${MINIZINC_OUTPUT}" | grep -q "${EXPECTED_ERROR}"; then
#     echo "SUCCESS: Expected bug demonstrated! MiniZinc reported 'undefined identifier'."
#     exit 0
# else
#     echo "FAILURE: Expected bug NOT demonstrated. MiniZinc did not report 'undefined identifier' or reported a different error."
#     echo "MiniZinc Exit Code: ${MINIZINC_EXIT_CODE}"
#     exit 1
# fi

