[package]
name = "zos-stage-doh"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zos-stage-doh"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
clap = { version = "4.5.4", features = ["derive"] }
git2 = "0.19.0"
