[package]
name = "poem_macro_impl_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
linkme = "0.3"

poem_macro_impl = { path = "../poem_macro_impl" }
syn = { version = "2.0", features = ["full"] }
