[package]
name = "kantspel_macros"
version = "0.1.0"
edition = "2021"

[dependencies]
poem_macros = { path = "../poem_macros" }
anyhow = "1.0"
regex = "1.0"
gemini_utils = { path = "../gemini_utils" }
poem_traits = { path = "../poem_traits" }