#!/bin/bash

# This script generates pub use statements for lib.rs based on the file structure.
# It should be run from the project root.

LIB_RS_DIR="tools/minizinc_ffi/src"

echo "// Generated by generate_pub_uses.sh - DO NOT EDIT MANUALLY"
echo ""

# Find all .rs files directly under LIB_RS_DIR, excluding lib.rs
find "$LIB_RS_DIR" -maxdepth 1 -type f -name "*.rs" ! -name "lib.rs" | sort | while read -r file; do
    module_name=$(basename "$file" .rs)
    echo "pub mod ${module_name};"
    echo "pub use ${module_name}::*;"
    echo ""
done

# Find all subdirectories under LIB_RS_DIR, excluding feature_tests
find "$LIB_RS_DIR" -maxdepth 1 -type d ! -name "$(basename "$LIB_RS_DIR")" ! -name "feature_tests" | sort | while read -r dir; do
    module_name=$(basename "$dir")
    echo "pub mod ${module_name};"
    echo "pub use ${module_name}::*;"
    echo ""
done
