// This file is automatically generated by the Gemini CLI.
// It contains named character constants for "kantspel" transformation.

// Basic ASCII and common programming characters
pub mod level10;
pub mod constants;
pub use level10::*;
pub use constants::*;
pub mod clean_non_ascii;
pub use clean_non_ascii::clean_non_ascii;
