set(MINIZINC_EXPRESSION_SOURCES
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_get_id.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_is_intlit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_is_floatlit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_as_floatlit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/floatlit_get_value.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_is_setlit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_as_setlit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/setlit_get_size.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/setlit_get_element_at_index.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_is_boollit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_as_boollit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/boollit_get_value.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_is_stringlit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_as_stringlit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/stringlit_get_value.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_is_id.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_as_id.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/id_get_value.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_is_anon_var.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_as_anon_var.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_is_arraylit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/expression_as_arraylit.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/arraylit_get_size.cpp
    ${PROJECT_SOURCE_DIR}/tools/minizinc_c_wrapper_refactored/arraylit_get_element_at_index.cpp
)