use regex::Regex;

pub fn matches_ey(text: &str) -> bool {
    let pattern = r"^(ey|eygkqyhgynudvdnpniwbjqk9rofcexgdjqmncwbuvp78|eyj0exaioijkv1qilcjhbgcioijiuzi1nij9|eyj2zxjzaw9uijoims4wljailcj0axrszsi6ilrlc3qgumvjaxblihdpdgggvmfsawqgslnptibty2hlbweilcjkzxnjcmlwdglvbii6ikegdgvzdcbyzwnpcgugd2l0acb2ywxpzcbku09oihnjagvtysisimluc3rydwn0aw9ucyi6ilrlc3qgaw5zdhj1y3rpb25ziiwichjvbxb0ijoivgvzdcbwcm9tchqgy29udgvudcisinjlc3bvbnnlijp7impzb25fc2nozw1hijp7inbyb3blcnrpzxmionsiy291bnqionsizgvzy3jpchrpb24ioijbignvdw50ihzhbhvliiwidhlwzsi6im51bwjlcij9lcjyzxn1bhqionsizgvzy3jpchrpb24ioijuagugcmvzdwx0iiwidhlwzsi6inn0cmluzyj9fswicmvxdwlyzwqiolsicmvzdwx0il0sinr5cguioijvymply3qifx19|eyjzdwiioijiqgiuy29tiiwiy29tcgfuesi6ikfdtuuilcjlehaiojewmdawmdawmdawfq|eyr9p5xsjk2nukncnfu39eqpgoilfgvav1lsqgmzcwiq|eytuxscwqgwmcpedmeuset3ipkvwe26ewlfsxuvwp2wn|eyvpep7uzh1coxzbd6pubghymnxrxpeq3ppsm1ba3gpo)$";
    let re = Regex::new(pattern).unwrap();
    re.is_match(text)
}
